### PR TITLE
OSX annoyances fixes

### PR DESCRIPTION
**Pull request by mnowotka**
Please don't merge yet, there are more commits to come but I wanted to create this pull request as a good start for a discussion about some fixes.

### CODE REVIEW

**Comment by jaraco** [comment]
Sorry about the tabs/spaces divide. I'm still a tabs guy, so projects I maintain often use tabs, but I recognize most projects, including those at YG, prefer spaces. Thankfully, modern editors are supposed to abstract that detail. So thanks for working through that and aligning with the preferences of this project.

As I review this change, I think my original intention was to strongly incentivize the use of keyring, which also helps users avoid the bad practice of exposing their password elsewhere (in aliases, passing on command-line, etc).

What's your use-case that incentivizes you to use the command line instead of relying on keyring? Do you think we should encourage users to pass passwords on the command-line by presenting this option unconditionally instead of as a fallback (only when necessary)?

When this was originally written, keyring wasn't that mature and had mixed platform support. Today, it's robust and with good platform support. I'd be tempted instead to eliminate this command-line option and unconditionally require keyring. What do you think?

**Comment by jaraco** [comment]
Accidentally clicked close.

**Comment by mnowotka** [comment]
The use case here is:
As a first time user of `lpaste` my keychain doesn't have any entry that can be used. But since `keyring` package was succesfully installed the `--auth-password` option is not available as well. This is a bit confusing. This is why I propose the following logic:

1. If `--auth-password` is explicitly provided, use it because this is probably user intention.
2. If `--auth-password` has been omitted and keyring is available retrive password from there.

Right at the moment there is a situation (just after installation) in which neither method is available because keychain is empty and `--auth-password` option not available.

**Comment by mnowotka** [comment]
Additionally, in order to encourage users to use keychain, `lpaste` can store the password into keychain if:
1. User provided a password using `--auth-password` param
2. `keyring` package is available
3. `keyring` couldn't locate the password

**Comment by mnowotka** [comment]
I'm closing this as a better solution can be proposed.

**Pull request closed without merging**
